### PR TITLE
Upgrade to Dotnet standard 2.0

### LINKED ISSUE #4: winform sample action bug
in winform sample multilevelundo textbox changes after undo will cause history mess.
take c for changes (actions): c1>c2>c3>undo>c4 by then c3 shall be removed from history while actually not, after another undo the history return c3 which should be c2.

### PR DESCRIPTION
**Pull request by tzachshabtay**
- Upgrade undo framework to dotnet standard 2.0
- Tests- Move from MSTest to NUnit (to allow running tests on mac/linux)
- Upgrade samples to dotnet 4.7.1 (to be able to reference undo framework)
- Fix #4

### CODE REVIEW

**Review by KirillOsenkov — APPROVED** [review]

**Comment by KirillOsenkov** [comment]
Thanks for the contribution!

**Comment by tzachshabtay** [comment]
Sure, any chance of getting this on nuget anytime soon?

Thanks.

**Comment by KirillOsenkov** [comment]
Here you go, hope it works for you: https://www.nuget.org/packages/GuiLabs.Undo/1.0.2

**Comment by tzachshabtay** [comment]
Thanks, I'll give it a go once I have time (and when the nuget index refreshes) and let you know.

**Comment by tzachshabtay** [comment]
Tested, it works fine, thanks.

**Pull request merged**
